// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	getSaveFiles: () => typedError<SaveFile[], string>(__TAURI_INVOKE("get_save_files")),
	loadSaveFile: (path: string, storefront: Storefront) => typedError<null, string>(__TAURI_INVOKE("load_save_file", { path, storefront })),
	getDisplayNames: (storefront: Storefront) => typedError<{ [key in number]: string }, AppError>(__TAURI_INVOKE("get_display_names", { storefront })),
	getSnapshot: () => typedError<Snapshot, AppError>(__TAURI_INVOKE("get_snapshot")),
};

/** Events */
export const events = {
	saveChanged: makeEvent<SaveChanged>("save-changed"),
};

/* Types */
export type AppError = ({ Io: string }) & { NotFound?: never; Parse?: never } | ({ Parse: string }) & { Io?: never; NotFound?: never } | ({ NotFound: string }) & { Io?: never; Parse?: never } | "NoSaveLoaded";

export type ChecklistFacts = {
	moonstoneChestBiomes: (string | null)[],
	riftBiomes: (string | null)[],
	dreamSnaps: DreamSnaps | null,
	scroogeStores: ScroogeStore[],
	starPaths: StarPath[],
};

export type Critter = {
	itemId: number,
	name: string,
	species: string,
	speciesRank: number,
	biome: string,
	notes: string[],
	schedule: Schedule[][],
	tamed: boolean,
	lastFeedingSecs: number | null,
};

export type DreamSnaps = {
	submitNeeded: boolean,
	voteNeeded: boolean,
};

export type GiftCategory = "produce" | "meal" | "flower" | "fish" | "animalProduct" | "gem" | "material" | "other";

export type PreferredGift = {
	itemId: number,
	name: string,
	category: GiftCategory,
	discovered: boolean,
	gifted: boolean,
};

export type Role = "gardening" | "fishing" | "mining" | "foraging" | "digging" | "timebending" | "snippetCatching";

export type SaveChanged = Snapshot;

export type SaveFile = {
	path: string,
	storefront: Storefront,
	lastModified: number,
};

export type Schedule = {
	start: number,
	end: number,
};

export type ScroogeItem = {
	id: number,
	name: string,
};

export type ScroogeStore = {
	location: string | null,
	newItems: ScroogeItem[],
};

export type Section<T> = { status: "ok"; data: T } | { status: "error"; error: string };

export type Snapshot = {
	tzOffset: number,
	modifiedSecs: number,
	critters: Section<Critter[]>,
	villagers: Section<Villager[]>,
	checklist: Section<ChecklistFacts>,
};

export type StarPath = {
	name: string,
	duties: StarPathDuty[],
};

export type StarPathDuty = {
	description: string,
	progress: number,
	target: number,
};

export type Storefront = "steam" | "epic" | "microsoft";

export type Villager = {
	id: number,
	name: string,
	role: Role | null,
	friendshipLevel: number,
	friendshipXp: number,
	isMaxed: boolean,
	gifts: PreferredGift[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

